# workflow의 이름
name: build_deploy

# 환경 변수 $변수명 으로 사용
# ex) $PROJECT_NAME
env: 
  PROJECT_NAME : ExampleAwsCodeDeploy
  BUCKET_NAME : webservice-deploy-storage
  
# 특정한 이벤트(조건)에 workflow를 실행시키는 트리거
# master 브런치에 push할 때 동작
on:
  push:
    branches: [ master ]

# 하나 이상의 실행할 작업(Job)과 그 작업(Job)을 실행할 환경
jobs:
  # 빌드와 배포를 할 작업인 job
  build_and_deploy:
    
    # 작업을 시스템 유형 (ubuntu)
    runs-on: ubuntu-latest
    
    # Job이 포함하고있는 일련의 업무들(steps) 
    steps:
    # 워크플로가 쓰인 프로젝트의 github 저장소의 $GITHUB_WORKSPACE에 접근할 수 있게 해줌
    # https://github.com/actions/checkout 
    - name: Checkout github workspace
      uses: actions/checkout@v2
    
    # Java파일 사용을 위한 Java 환경을 다운로드
    # https://github.com/actions/setup-java
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        java-package: jdk 
        architecture: x64

    # gradlew 실행권한 주기
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      shell: bash
    
    # 빌드하기
    - name: Build with Gradle
      run: ./gradlew build
      shell: bash
    
    # zip으로 압축
    # 현재 directory를 현재 경로에 build.zip 이름으로 압축
    # -r 하위경로까지 모두다라는 옵션 
    - name: Compress the result into zip file
      run: zip -r ./build.zip .
      shell: bash
    
    # aws 인증서비스
    # github repository에서 Setting에서 사용할 암호화된 변수
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION}}
    
    # Upload to S3 stroage
    - name: Upload to S3
      run: aws s3 cp build.zip s3://$BUCKET_NAME/deploy/$PROJECT_NAME.zip --region ap-northeast-2        
    
    # AWS CodeDeploy 실행 
    - name: Code Deploy
      run: aws deploy create-deployment --application-name WebserviceCodeDeploy --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name WebserviceCodeDeployDeployGroup --s3-location bucket=$BUCKET_NAME,bundleType=zip,key=deploy/$PROJECT_NAME.zip
