# workflow의 이름, 생략하면 위의 파일이름
name: Build and Deploy AWS Ec2 

# 특정한 이벤트(조건)에 workflow를 실행시키는 트리거
# 아래의 코드는 master 브런치에 push할 때 동작
on:
  push:
    branches: [ master ]

# 하나 이상의 실행할 작업(Job)과 그 작업(Job)을 실행할 환경
jobs:
  # 'build and deploy'라는 Job_id를 가진 하나의 job
  build_and_deploy:
    # 작업을 실행할 환경 (ubuntu)
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # github 저장소의 $GITHUB_WORKSPACE에 접근할 수 있게 checkout
    # https://github.com/actions/checkout 
    - name: Checkout github workspace
      uses: actions/checkout@v2
    
    # 자바파일 실행 위해 jdk 설치
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        java-package: jdk 
        architecture: x64

    # gradlew 실행권한 주기
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      shell: bash
    
    # 빌드하기
    - name: Build with Gradle
      run: ./gradlew build
      shell: bash
